version: '3.9'

services:
  node-lambda-app:
      container_name: node-lambda-app
      image: infuse-ai
      ports:
        - 8080:8080
      env_file:
        - .env
      environment:
      - DYNAMODB_ENDPOINT=http://dynamodb-local:9000
      - CHROMA_URL=http://chroma:8000
      - APP_TIMEZONE=IST
      - APP_PORT=8080
      networks:
      - infuse-net

networks:
  infuse-net:
    driver: bridge